In [50]:
print("Hello World!")

Hello World!

### Pandas Assignment

In [34]:
import pandas as pd

# ----------------   TASK-1 --------------------
print("----------------   TASK-1 --------------------")
# Create a pandas series from list
marks=[78,85,90,66,72]
marks=pd.Series(marks, dtype='int32')
print("Series:")
print(marks)
print("First element: ",marks[0])
print("Last two element: ",marks[3:].values)

----------------   TASK-1 --------------------
Series:
0    78
1    85
2    90
3    66
4    72
dtype: int32
First element:  78
Last two element:  [66 72]

In [35]:
# ----------------   TASK-2 --------------------
print("----------------   TASK-2 --------------------")
# add 5 garce mark to all studnets

marks= marks+5

print("Marks after grace of 5: ", marks.values)

marks=marks-2
print("Marks after -2: ", marks.values)

marks=marks*1.05
print("Marks after *1.05: ", marks.values)

marks=marks/2
print("Marks after /2: ", marks.values)

----------------   TASK-2 --------------------
Marks after grace of 5:  [83 90 95 71 77]
Marks after -2:  [81 88 93 69 75]
Marks after *1.05:  [85.05 92.4  97.65 72.45 78.75]
Marks after /2:  [42.525 46.2   48.825 36.225 39.375]

In [36]:
# ----------------   TASK-3 --------------------
print("----------------   TASK-3 --------------------")

# Again initialising the mark
marks=[78,85,90,66,72]
marks=pd.Series(marks, dtype='int32')
print("Series:", marks.values, type(marks))

print("Max in Marks: ", marks.max())
print("Min in Marks: ", marks.min())
print("Sum in Marks: ", marks.sum())
print("Mean in Marks: ", marks.mean())

print("Passed Student", marks[marks>=70].values)

print("Count of Passed Student:", marks[marks>=70].value_counts().size)

----------------   TASK-3 --------------------
Series: [78 85 90 66 72] <class 'pandas.Series'>
Max in Marks:  90
Min in Marks:  66
Sum in Marks:  391
Mean in Marks:  78.2
Passed Student [78 85 90 72]
Count of Passed Student: 4

In [37]:
# ----------------   TASK-4 --------------------
print("----------------   TASK-4 --------------------")
student={'Name':['Amit','Neha','Rahul','Sneha','Pooja'], 'Marks':[78,85,90,66,72],'Subject':['Math','Math','Science','Science','Math']}
print(student)

df=pd.DataFrame(student)
print("PD DataFrame:")
print(df, type(df))

print("First 3 Row from DataFrame:")
print(df[:3:1])

print("Last 2 Row from DataFrame:")
print(df[3::])

print("Shape of the DataFrame: ",df.shape)

print("Columns in the DataFrame: ",df.columns)

----------------   TASK-4 --------------------
{'Name': ['Amit', 'Neha', 'Rahul', 'Sneha', 'Pooja'], 'Marks': [78, 85, 90, 66, 72], 'Subject': ['Math', 'Math', 'Science', 'Science', 'Math']}
PD DataFrame:
    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math <class 'pandas.DataFrame'>
First 3 Row from DataFrame:
    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
Last 2 Row from DataFrame:
    Name  Marks  Subject
3  Sneha     66  Science
4  Pooja     72     Math
Shape of the DataFrame:  (5, 3)
Columns in the DataFrame:  Index(['Name', 'Marks', 'Subject'], dtype='str')

In [38]:
# ----------------   TASK-5 --------------------
print("----------------   TASK-5 --------------------")

# Using same dataframe of student from Task-4
print(df.info())

print(df.describe())

print(df.head(2))

print(df.tail(2))

df1=df.sort_values('Marks',ascending=False)
df1

----------------   TASK-5 --------------------
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      str
 1   Marks    5 non-null      int64
 2   Subject  5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes
None
           Marks
count   5.000000
mean   78.200000
std     9.654015
min    66.000000
25%    72.000000
50%    78.000000
75%    85.000000
max    90.000000
   Name  Marks Subject
0  Amit     78    Math
1  Neha     85    Math
    Name  Marks  Subject
3  Sneha     66  Science
4  Pooja     72     Math

    Name  Marks  Subject
2  Rahul     90  Science
1   Neha     85     Math
0   Amit     78     Math
4  Pooja     72     Math
3  Sneha     66  Science

In [39]:
# ----------------   TASK-6 --------------------
print("----------------   TASK-6 --------------------")

df[df['Marks'] > 75]

----------------   TASK-6 --------------------

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science

In [40]:
df[df['Subject']=='Math']

    Name  Marks Subject
0   Amit     78    Math
1   Neha     85    Math
4  Pooja     72    Math

In [41]:
df[df['Marks'] > df['Marks'].mean()]

    Name  Marks  Subject
1   Neha     85     Math
2  Rahul     90  Science

In [42]:
df[df['Marks'] < 70 ]

    Name  Marks  Subject
3  Sneha     66  Science

In [ ]:
# find average marks per subject using groupby()

<bound method DataFrame.groupby of     Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math>